### PR TITLE
Refactor `pageant` to be an importable package

### PR DESCRIPTION
**Pull request by hslatman**
A new `Pageant` struct wraps the configuration and proxy logic. A new instance can be created with `pageant.New`. The Pageant proxy can then be started using `Run()`.

This makes it easier to embed the functionality in another application, such as a custom SSH agent implementation.

### CODE REVIEW

**Comment by ndbeals** [comment]
This is an awesome idea! thanks for the work. I didn't think anyone would want an importable package out of this functionality but it appears I'm wrong.

I'm on lunch right now so I won't get time to in-depth review this, but I did take a cursory glance. Nothing immediately pops out as wrong, so that's great. I have some questions/discussion for you though:

- Have you built this and ran/tested it locally? (I know I need to write integration tests for this)
- Out of curiousity, what project are you trying to use this new `pageant` package in?

I'd like to make what `wndProc` does with the data it receives configurable. I.E we give the Pageant struct a function handler (something like `handlerFunc Func([]byte)`) and call it on line `run_windows.go:213`, and we move the lines below that into the default `handlerFunc`.

**Comment by hslatman** [comment]
>     * Have you built this and ran/tested it locally? (I know I need to write integration tests for this)
Yes, compiled it for a Windows VM, configured Putty for `git@github.com` and loaded a test SSH key with `ssh-add`. Connection was successful 🙂. Haven't tested packaging it, but that should just work. 

>     * Out of curiousity, what project are you trying to use this new `pageant` package in?
I have several ideas that revolve around SSH agents, and I would like them to work on Windows without having to install separate binaries. The most concrete is the ecosystem we're building at Smallstep, amongst which is the CLI: https://github.com/smallstep/cli. We already have some integrations with OpenSSH, and our CLI generally works well on Windows, but people are still often using Putty for SSH. It may be an option to include this functionality in the CLI (or a different component) to make it easier for people to use Putty with the rest of our ecosystem. Combining that with [SSH certificates in Putty](https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/putty-certificates/), which we're strong proponents of, might be even more fun. Another potential application may be to add support to https://github.com/FiloSottile/yubikey-agent. Windows support is WIP; embedding this for Putty support might be nice. 

> I'd like to make what `wndProc` does with the data it receives configurable. I.E we give the Pageant struct a function handler (something like `handlerFunc Func([]byte)`) and call it on line `run_windows.go:213`, and we move the lines below that into the default `handlerFunc`.
If I understand you correctly you want the `handlerFunc` to be called with `result`? And by default that should only do the `copy(sharedMemoryArray[:], result)`? The rest of the code is only cleanup; and the `sharedMemoryArray` actually needs setup before the call, so doesn't seem suitable to put in the `handlerFunc` itself?. I can imagine just calling the `handlerFunc` to be used like a callback with `result`, then continue with the cleanup as it is right now.

As a preparation for this change I've made `New` a variadic function taking options.

**Comment by ndbeals** [comment]
> Yes, compiled it for a Windows VM, configured Putty for git@github.com and loaded a test SSH key with ssh-add. Connection was successful 🙂

Awesome, thank you.

> If I understand you correctly you want the `handlerFunc` to be called with `result`?

Close, very close. You did a good job interpreting my rushed lunch response. Here's what I imagined:

Original:

``` go
size := binary.BigEndian.Uint32(sharedMemoryArray[:4]) + 4 // +4 for the size uint itself
if size > sshagent.AgentMaxMessageLength {
    return 0
}

// Query the windows OpenSSH agent via the windows named pipe
result, err := sshagent.QueryAgent(p.sshPipe, sharedMemoryArray[:size])
if err != nil {
    log.Println(err)
    return 0
}
copy(sharedMemoryArray[:], result)
```

With a handler func:

``` go
size := binary.BigEndian.Uint32(sharedMemoryArray[:4]) + 4 // +4 for the size uint itself
if size > sshagent.AgentMaxMessageLength {
    return 0
}

result, err := p.HandlerFunc(sharedMemoryArray[:size])
if err != nil {
    log.Println(err)
    return 0
}

copy(sharedMemoryArray[:], result)
```

Where the signature of `p.HandlerFunc` is `func(p *Pageant, pageantResult []byte) ([] byte, err)`

And the default `HandlerFunc` is

``` go
result, err := sshagent.QueryAgent(p.sshPipe, sharedMemoryArray[:size])
```

The names of the function/variable names is just to illustrate meaning, I'm not married to them being that exact name, but I hope I got my meaning across.

Are you okay with me committing changes to this branch too (that is, if you haven't made these above changes before I get to it)?

**Comment by hslatman** [comment]
Hey @ndbeals, I added the `HandlerFunc` like you described above. Via an `Option` is not likely to work, because of the function signature. It's calling a method on `p` with `p` as the first argument. If provided through `New()`, then `p` is not yet known, so that doesn't work. 

Maybe there's a way to make this work via `New` with some more refactoring or if the SSH pipe name is passed instead of `p`.

Feel free to commit to this branch 🙂

**Comment by hslatman** [comment]
Hey @ndbeals, what are your thoughts on my latest changes and the proposed options? Without doing some more refactoring, it'll remain a bit messy. It works, but could be made a bit more neat, I guess 🙂

**Comment by ndbeals** [comment]
Sorry this took me so long @hslatman. I've made some changes and I'm going to merge this.

**Comment by hslatman** [comment]
Thank you, @ndbeals! 

Changes look OK and usable to me 🙂

**Pull request merged**
